CREATE DATABASE KostKompas;

USE KostKompas;

CREATE TABLE USERS(
user_id INT PRIMARY KEY IDENTITY (1,1),
NAME VARCHAR(255) NOT NULL,
Email VARCHAR(255) UNIQUE,
Password VARCHAR(255) NOT NULL,
Kcal_goal DECIMAL NOT NULL,
Protein_goal DECIMAL NOT NULL,
Carbo_goal DECIMAL NOT NULL,
Fat_goal DECIMAL NOT NULL,
Fibre_goal DECIMAL NOT NULL
);

CREATE TABLE FOODS(
food_id INT PRIMARY KEY IDENTITY (1,1),
user_id INT FOREIGN KEY references USERS(user_id) ON DELETE SET NULL,
Name VARCHAR(255) NOT NULL,
Kcal DECIMAL NOT NULL,
Protein DECIMAL NOT NULL,
Fat DECIMAL NOT NULL,
Carbohydrates DECIMAL NOT NULL,
Fibre DECIMAL NOT NULL
);

CREATE TABLE MEAL_names(
meal_id INT PRIMARY KEY IDENTITY (1,1),
Name VARCHAR(255) NOT NULL
);

CREATE TABLE EATEN(
eaten_id INT PRIMARY KEY IDENTITY (1,1),
user_id INT FOREIGN KEY references USERS ON DELETE CASCADE,
food_id INT FOREIGN KEY references FOODS ON DELETE CASCADE,
meal_id INT FOREIGN KEY references MEAL_names ON DELETE NO ACTION,
date date NOT NULL,
weight DECIMAL NOT NULL
);